#!/usr/bin/env python3
"""
Compare current perf results against a baseline and report regressions.

Baseline and current are JSON files generated by bench_perf.py.
"""

from __future__ import annotations

import argparse
import json
import sys
from typing import Any, Dict, Tuple


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--baseline", required=True, help="Path to baseline perf_results.json")
    p.add_argument("--current", required=True, help="Path to current perf_results.json")
    p.add_argument(
        "--threshold",
        type=float,
        default=0.05,
        help="Relative regression threshold (e.g., 0.05 = +5%% allowed)",
    )
    return p.parse_args()


def load(path: str) -> Dict[str, Any]:
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def index_by_name(data: Dict[str, Any]) -> Dict[str, Dict[str, Any]]:
    return {c["aggregate"]["name"]: c["aggregate"] for c in data.get("cases", [])}


def compare_case(
    name: str,
    base: Dict[str, Any],
    cur: Dict[str, Any],
    threshold: float,
) -> Tuple[bool, str]:
    """
    Returns (is_regression, message)
    """
    base_time = base.get("wall_ms")
    cur_time = cur.get("wall_ms")
    if base_time is None or cur_time is None:
        return False, f"{name}: missing wall_ms in baseline/current"

    # Only consider cases that passed in both runs
    if base.get("status") != "ok" or cur.get("status") != "ok":
        return False, f"{name}: skipped (non-ok status)"

    if base_time <= 0:
        return False, f"{name}: baseline wall_ms <= 0"

    delta = (cur_time - base_time) / base_time
    if delta > threshold:
        return True, f"{name}: wall_ms regression {delta*100:.1f}% (base {base_time:.2f}, cur {cur_time:.2f})"
    return False, f"{name}: within threshold (delta {delta*100:.1f}%)"


def main() -> int:
    args = parse_args()
    baseline = load(args.baseline)
    current = load(args.current)

    base_idx = index_by_name(baseline)
    cur_idx = index_by_name(current)

    regressions = []
    notes = []

    for name, base_case in base_idx.items():
        cur_case = cur_idx.get(name)
        if not cur_case:
            notes.append(f"{name}: missing in current run")
            continue
        is_reg, msg = compare_case(name, base_case, cur_case, args.threshold)
        if is_reg:
            regressions.append(msg)
        else:
            notes.append(msg)

    if regressions:
        print("Performance regressions detected:")
        for r in regressions:
            print(f"- {r}")
        for n in notes:
            print(f"Note: {n}")
        return 1

    print("No regressions detected.")
    for n in notes:
        print(f"Note: {n}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
